export enum AppRoutes {
  NOT_FOUND = 'NOT_FOUND',
  FRONTEND_HOME = 'FRONTEND_HOME',
  FRONTEND_MENU = 'FRONTEND_MENU',
  FRONTEND_OFFERS = 'FRONTEND_OFFERS',
  ADMIN_DASHBOARD = 'ADMIN_DASHBOARD',
  ADMIN_MENU_CATEGORY = 'ADMIN_MENU_CATEGORY'
}
